"""
Reporter node - generates the final research report.

Synthesizes all completed research steps into a comprehensive report.
"""

import logging
from typing import Literal

from langchain_core.messages import AIMessage, SystemMessage
from langgraph.types import Command

from backend.agents.state import ResearchState
from backend.core.llm import get_llm

logger = logging.getLogger(__name__)

REPORTER_PROMPT = """You are the Reporter for a deep research system.

Your job is to create a comprehensive research report based on the completed research.

ORIGINAL RESEARCH QUERY:
{original_query}

COMPLETED RESEARCH FINDINGS:
{research_findings}

YOUR TASK:
Create a well-structured Markdown report that:
1. Directly addresses the original query
2. Synthesizes key findings from all research steps
3. Provides clear, actionable insights
4. Uses proper Markdown formatting (headers, lists, etc.)
5. Cites sources where available

REPORT STRUCTURE:
# Research Report: [Topic]

## Executive Summary
[Brief overview of key findings]

## Detailed Findings
[Organized by theme or research step]

## Key Insights
[Most important takeaways]

## Sources
[List of sources if available]

---
*Generated by damn-so-deep-research*

Write the report in the same language as the original query."""


async def reporter_node(
    state: ResearchState,
) -> Command[Literal["__end__"]]:
    """
    Generates the final research report.

    Synthesizes all DONE steps into a comprehensive Markdown report.
    If all steps failed, generates an apology message instead.
    """
    run_id = state["run_id"]
    plan = state["plan"]
    original_query = state["original_query"]
    recovery_attempts = state.get("recovery_attempts", 0)

    logger.info(f"Reporter generating report for run {run_id}")

    # Gather completed research
    completed_findings = []
    failed_steps = []
    for step in plan:
        if step["status"] == "DONE" and step.get("result"):
            completed_findings.append(
                f"### {step['description']}\n{step['result']}"
            )
        elif step["status"] == "SKIPPED":
            completed_findings.append(
                f"### {step['description']}\n*Skipped: {step.get('result', 'Not critical')}*"
            )
        elif step["status"] == "FAILED":
            failed_steps.append(step["description"])

    # Check if this is a failure case (no useful findings after max retries)
    if not completed_findings and (failed_steps or recovery_attempts >= 2):
        logger.warning(f"Research failed: {len(failed_steps)} failed steps, {recovery_attempts} recovery attempts")

        # Generate failure message without calling LLM (to avoid hallucination)
        failed_list = "\n".join(f"- {s}" for s in failed_steps) if failed_steps else "- Поиск не дал результатов"
        report = f"""# Результаты исследования

К сожалению, не удалось найти информацию по вашему запросу.

**Исходный запрос:** {original_query}

**Что пошло не так:**
{failed_list}

Система выполнила несколько попыток поиска с разными формулировками запросов, но не смогла получить релевантные результаты.

**Рекомендации:**
- Попробуйте переформулировать запрос более конкретно
- Укажите дополнительный контекст или ключевые слова
- Разбейте сложный вопрос на несколько простых

---
*Generated by damn-so-deep-research*"""
    else:
        if not completed_findings:
            findings_text = "No research findings were collected."
        else:
            findings_text = "\n\n".join(completed_findings)

        # Generate report
        llm = get_llm(temperature=0.3)  # Slight creativity for writing
        messages = [
            SystemMessage(
                content=REPORTER_PROMPT.format(
                    original_query=original_query,
                    research_findings=findings_text,
                )
            ),
        ]

        response = await llm.ainvoke(messages)
        report = response.content

    logger.info(f"Report generated: {len(report)} characters")

    return Command(
        update={
            "phase": "done",
            "messages": [
                AIMessage(content=report, name="Reporter"),
            ],
        },
        goto="__end__",
    )
