"""
Reporter node - generates the final research report.

Synthesizes all completed research steps into a comprehensive report.
"""

import logging
from typing import Literal

from langchain_core.messages import AIMessage, SystemMessage
from langgraph.types import Command

from backend.agents.state import ResearchState
from backend.core.llm import get_llm

logger = logging.getLogger(__name__)

REPORTER_PROMPT = """You are the Reporter for a deep research system.

Your job is to create a comprehensive research report based on the completed research.

ORIGINAL RESEARCH QUERY:
{original_query}

COMPLETED RESEARCH FINDINGS:
{research_findings}

YOUR TASK:
Create a well-structured Markdown report that:
1. Directly addresses the original query
2. Synthesizes key findings from all research steps
3. Provides clear, actionable insights
4. Uses proper Markdown formatting (headers, lists, etc.)
5. Cites sources where available

REPORT STRUCTURE:
# Research Report: [Topic]

## Executive Summary
[Brief overview of key findings]

## Detailed Findings
[Organized by theme or research step]

## Key Insights
[Most important takeaways]

## Sources
[List of sources if available]

---
*Generated by damn-so-deep-research*

Write the report in the same language as the original query."""


async def reporter_node(
    state: ResearchState,
) -> Command[Literal["__end__"]]:
    """
    Generates the final research report.

    Synthesizes all DONE steps into a comprehensive Markdown report.
    """
    run_id = state["run_id"]
    plan = state["plan"]
    original_query = state["original_query"]

    logger.info(f"Reporter generating report for run {run_id}")

    # Gather completed research
    completed_findings = []
    for step in plan:
        if step["status"] == "DONE" and step.get("result"):
            completed_findings.append(
                f"### {step['description']}\n{step['result']}"
            )
        elif step["status"] == "SKIPPED":
            completed_findings.append(
                f"### {step['description']}\n*Skipped: {step.get('result', 'Not critical')}*"
            )

    if not completed_findings:
        findings_text = "No research findings were collected."
    else:
        findings_text = "\n\n".join(completed_findings)

    # Generate report
    llm = get_llm(temperature=0.3)  # Slight creativity for writing
    messages = [
        SystemMessage(
            content=REPORTER_PROMPT.format(
                original_query=original_query,
                research_findings=findings_text,
            )
        ),
    ]

    response = await llm.ainvoke(messages)
    report = response.content

    logger.info(f"Report generated: {len(report)} characters")

    return Command(
        update={
            "phase": "done",
            "messages": [
                AIMessage(content=report, name="Reporter"),
            ],
        },
        goto="__end__",
    )
